"""
Vibe Coding Project Bootstrap & Hardware/Software Synchronization Engine.
Generates dual-folder projects (/firmware and /hardware), BOM manifests,
and synchronizes GPIO bindings between code and schematic notes.
"""

from __future__ import annotations
import csv
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional
from hardware.component_engine import component_engine


class VibeProjectBootstrap:
    """
    Manages dual-structure hardware + software projects and vibe coding pin binding.
    """

    def __init__(self, base_dir: Optional[str] = None):
        if base_dir is not None:
            self.base_dir = Path(base_dir).resolve()
        else:
            try:
                from core.data_hub import data_hub
                self.base_dir = data_hub.resolve("projects")
            except Exception:
                self.base_dir = Path("projects").resolve()
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def bootstrap_project(
        self,
        project_name: str,
        target_parent: Optional[str] = None,
        base_dir: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Creates full hardware + software project structure:
        - /projects/<name>/firmware/ (main.py, main.ino)
        - /projects/<name>/hardware/ (schematic_notes.md, BOM.csv)
        - /projects/<name>/README.md (architecture overview)
        """
        clean_name = re.sub(r"[^a-zA-Z0-9_\-]", "_", project_name.strip())
        parent_arg = target_parent or base_dir
        if parent_arg:
            parent = Path(os.path.expanduser(parent_arg)).resolve()
        else:
            parent = self.base_dir
        proj_dir = parent / clean_name

        firmware_dir = proj_dir / "firmware"
        hardware_dir = proj_dir / "hardware"

        firmware_dir.mkdir(parents=True, exist_ok=True)
        hardware_dir.mkdir(parents=True, exist_ok=True)

        # 1. Generate Starter README.md
        readme_path = proj_dir / "README.md"
        if not readme_path.exists():
            readme_content = f"""# Project: {clean_name}
> Hardware & Firmware Vibe Coding Blueprint generated by P.H.A.S.S

## 1. System Overview
- **Project Name**: {clean_name}
- **Architecture**: Dual-Domain Hardware + Embedded Firmware
- **Status**: Initialized

## 2. Directory Architecture
```
{clean_name}/
├── firmware/          # Microcontroller code (.ino, .py, .cpp, headers)
│   └── main.py        # Firmware entrypoint
├── hardware/          # Electrical schematics, calculations, and BOM
│   ├── schematic_notes.md
│   └── BOM.csv
└── README.md          # Architecture & documentation
```

## 3. Hardware Architecture & Power Budget
- **System Power**: Regulated 5V / 3.3V rails with decoupling capacitors (0.1µF ceramic).
- **Core Controller**: Microcontroller / Embedded SoC.
- **Peripheral Bus**: I2C, SPI, UART, PWM channels.

## 4. Firmware Build & Flash
- Python: `python firmware/main.py`
- C++/Arduino: Compile via Arduino CLI / PlatformIO.
"""
            readme_path.write_text(readme_content, encoding="utf-8")

        # 2. Generate Schematic Notes (hardware/schematic_notes.md)
        schematic_path = hardware_dir / "schematic_notes.md"
        if not schematic_path.exists():
            schematic_content = f"""# Hardware Schematic & Wiring Notes: {clean_name}

## 1. Power Distribution Network (PDN)
- **Primary Input**: 5V DC (USB or external supply).
- **Regulated Rails**: 
  - +5.0V Rail: Main power bus.
  - +3.3V Rail: Clean digital logic and sensor bus.
- **Decoupling Strategy**: 
  - 100nF (0.1µF) ceramic capacitors placed within 5mm of every IC power pin.
  - 47µF bulk electrolytic capacitor across power entry.

## 2. Pinout & GPIO Allocation Table
| Subsystem / Peripheral | Controller Pin | Function / Mode | Active State | Notes |
|------------------------|----------------|-----------------|--------------|-------|
| Status LED             | GPIO 2 / Pin 13| OUTPUT (PWM)    | Active HIGH  | 220Ω current limiting resistor |
| System Reset           | /RESET         | INPUT_PULLUP    | Active LOW   | 10kΩ pull-up to Vcc |

## 3. Circuit Safety & Protection
- Reverse polarity protection diode (1N4007 or Schottky 1N5819) at DC input.
- Flyback suppression diode across all inductive actuators (relays, solenoids, motors).
- Pull-down resistors (10kΩ) on all MOSFET gate drive lines to prevent floating gate conduction.
"""
            schematic_path.write_text(schematic_content, encoding="utf-8")

        # 3. Generate Bill of Materials (hardware/BOM.csv)
        bom_path = hardware_dir / "BOM.csv"
        if not bom_path.exists():
            with open(bom_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow(["Item #", "Designator", "Component Description", "Package", "Quantity", "Notes / Sourcing"])
                writer.writerow(["1", "C1, C2", "0.1uF Ceramic Capacitor 50V", "Radial 2.54mm", "2", "Power decoupling near MCU"])
                writer.writerow(["2", "R1", "220 Ohm 1/4W Resistor", "Through-Hole", "1", "LED current limiter"])
                writer.writerow(["3", "D1", "Status LED (Red 5mm)", "Through-Hole", "1", "Vf=2.0V, If=20mA"])

        # 4. Generate Starter Firmware (firmware/main.py and firmware/main.ino)
        py_main = firmware_dir / "main.py"
        if not py_main.exists():
            py_code = f"""\"\"\"
{clean_name} - Main Firmware Entrypoint (MicroPython / CircuitPython)
Hardware Co-Pilot generated template
\"\"\"
import time

LED_PIN = 2  # Default status LED pin

def setup():
    print("[{clean_name}] Hardware initialized.")
    # On MicroPython:
    # from machine import Pin
    # led = Pin(LED_PIN, Pin.OUT)

def loop():
    print("[{clean_name}] System loop ticking...")
    time.sleep(1)

if __name__ == '__main__':
    setup()
    while True:
        loop()
"""
            py_main.write_text(py_code, encoding="utf-8")

        ino_main = firmware_dir / "main.ino"
        if not ino_main.exists():
            ino_code = f"""/*
 * {clean_name} - Arduino / C++ Firmware Entrypoint
 */

const int LED_PIN = 13; // Status LED

void setup() {{
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  Serial.println("[{clean_name}] System Boot Complete.");
}}

void loop() {{
  digitalWrite(LED_PIN, HIGH);
  delay(500);
  digitalWrite(LED_PIN, LOW);
  delay(500);
}}
"""
            ino_main.write_text(ino_code, encoding="utf-8")

        return {
            "status": "SUCCESS",
            "project_name": clean_name,
            "project_dir": str(proj_dir),
            "firmware_dir": str(firmware_dir),
            "hardware_dir": str(hardware_dir),
            "files_created": [
                str(readme_path),
                str(schematic_path),
                str(bom_path),
                str(py_main),
                str(ino_main),
            ],
            "message": f"Hardware + Firmware project '{clean_name}' bootstrapped successfully.",
        }

    def add_component_to_project(self, project_name: str, component_name: str, notes: str = "") -> Dict[str, Any]:
        """
        Fetches component specifications and automatically adds it to
        schematic_notes.md and BOM.csv.
        """
        clean_name = re.sub(r"[^a-zA-Z0-9_\-]", "_", project_name.strip())
        proj_dir = self.base_dir / clean_name
        if not proj_dir.exists():
            # If project doesn't exist yet, bootstrap it first
            self.bootstrap_project(clean_name)

        datasheet = component_engine.fetch_datasheet(component_name)
        comp_data = datasheet.get("data", {})
        c_name = comp_data.get("name", component_name)
        c_type = comp_data.get("type", "Component")
        c_pkg = comp_data.get("package", "Standard")
        pinout_summary = ", ".join(comp_data.get("pin_labels", [])) or "Standard pinout"

        # 1. Append to BOM.csv
        bom_path = proj_dir / "hardware" / "BOM.csv"
        item_count = 1
        if bom_path.exists():
            with open(bom_path, "r", encoding="utf-8") as f:
                item_count = sum(1 for _ in f)

        with open(bom_path, "a", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow([str(item_count), f"U{item_count}", f"{c_name} ({c_type})", c_pkg, "1", notes or "Added via Vibe Coding"])

        # 2. Append to schematic_notes.md
        schematic_path = proj_dir / "hardware" / "schematic_notes.md"
        if schematic_path.exists():
            addition = f"""
### Added Component: {c_name}
- **Type**: {c_type}
- **Package**: {c_pkg}
- **Pinout Details**: {pinout_summary}
- **Key Specs**: {', '.join(f'{k}: {v}' for k, v in comp_data.get('key_specs', {}).items())}
- **Wiring Notes**: {notes or 'Connect decoupling capacitor and check pin 1 orientation.'}
"""
            with open(schematic_path, "a", encoding="utf-8") as f:
                f.write(addition)

        # 3. Add skeleton firmware/main.ino if component is a microcontroller like ESP32
        ino_path = proj_dir / "firmware" / "main.ino"
        if "esp32" in component_name.lower():
            esp32_skeleton = """// ESP32 Vibe Coding Firmware Skeleton
#include <Arduino.h>

const int LED_PIN = 2; // ESP32 built-in blue LED on GPIO2

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  Serial.println("ESP32 Initialized via P.H.A.S.S Vibe Coding.");
}

void loop() {
  digitalWrite(LED_PIN, HIGH);
  delay(500);
  digitalWrite(LED_PIN, LOW);
  delay(500);
}
"""
            ino_path.write_text(esp32_skeleton, encoding="utf-8")

        return {
            "status": "SUCCESS",
            "project_name": clean_name,
            "component": c_name,
            "bom_updated": str(bom_path),
            "schematic_updated": str(schematic_path),
            "message": f"Successfully integrated {c_name} into {clean_name} hardware architecture.",
        }

    def update_pin_binding(self, project_name: str, component_name: str, new_pin: str) -> Dict[str, Any]:
        """
        Vibe Coding synchronization:
        Updates both the firmware code (e.g. LED_PIN = 5) and the schematic notes!
        """
        clean_name = re.sub(r"[^a-zA-Z0-9_\-]", "_", project_name.strip())
        proj_dir = self.base_dir / clean_name
        if not proj_dir.exists():
            return {"status": "FAILED", "error": f"Project '{clean_name}' not found."}

        # Normalize pin representation (e.g., "5", "GPIO 5", "GPIO5", "D13")
        pin_num = re.search(r"\d+", new_pin)
        pin_val = pin_num.group(0) if pin_num else new_pin.strip()

        updates = []

        # 1. Update Python firmware (firmware/main.py)
        py_main = proj_dir / "firmware" / "main.py"
        if py_main.exists():
            content = py_main.read_text(encoding="utf-8")
            if "LED_PIN =" in content or "PIN =" in content:
                new_content = re.sub(r"(LED_PIN\s*=\s*)\d+", rf"\g<1>{pin_val}", content)
                py_main.write_text(new_content, encoding="utf-8")
                updates.append("firmware/main.py updated")

        # 2. Update Arduino / C++ firmware (firmware/main.ino)
        ino_main = proj_dir / "firmware" / "main.ino"
        if ino_main.exists():
            content = ino_main.read_text(encoding="utf-8")
            if "LED_PIN" in content:
                new_content = re.sub(r"(const\s+int\s+LED_PIN\s*=\s*)\w+;", rf"\g<1>{pin_val};", content)
                new_content = re.sub(r"(#define\s+LED_PIN\s+)\w+", rf"\g<1>{pin_val}", new_content)
                ino_main.write_text(new_content, encoding="utf-8")
                updates.append("firmware/main.ino updated")

        # 3. Update hardware/schematic_notes.md
        schematic_path = proj_dir / "hardware" / "schematic_notes.md"
        if schematic_path.exists():
            content = schematic_path.read_text(encoding="utf-8")
            note_line = f"- **Vibe Pin Update**: {component_name} re-routed to GPIO {pin_val}.\n"
            content += note_line
            schematic_path.write_text(content, encoding="utf-8")
            updates.append("hardware/schematic_notes.md updated")

        return {
            "status": "SUCCESS",
            "project_name": clean_name,
            "component": component_name,
            "new_pin": pin_val,
            "updates_performed": updates,
            "message": f"Synchronously bound {component_name} to GPIO {pin_val} in both firmware and hardware notes.",
        }


# Global singleton
vibe_bootstrap = VibeProjectBootstrap()
vibe_project_bootstrap = vibe_bootstrap

