# =============================================================================
# P.H.A.S.S EDGE BRAIN FIRMWARE (MicroPython v14.0 Omnipresent Architecture)
# Target Board: ESP32
# Auto-generated by hardware/edge_brain_generator.py
# =============================================================================

import time
import json
import socket
import select
try:
    import network
    from machine import Pin, ADC, PWM
except ImportError:
    class DummyPin:
        OUT = 1
        IN = 0
        def __init__(self, p, mode=None):
            self.p = p
            self.v = 0
        def value(self, v=None):
            if v is not None:
                self.v = v
            return self.v

    class DummyADC:
        def __init__(self, p):
            self.p = p
        def read(self):
            return 2048
        def read_u16(self):
            return 32768

    class DummyPWM:
        def __init__(self, p, freq=1000):
            self.p = p
            self.f = freq
            self.d = 0
        def freq(self, f=None):
            return self.f
        def duty(self, d=None):
            if d is not None:
                self.d = d
            return self.d
        def duty_u16(self, d=None):
            return self.duty(d)

    Pin, ADC, PWM = DummyPin, DummyADC, DummyPWM

# Wi-Fi & Broker Configuration
WIFI_SSID = "HomeNetwork_2.4G"
WIFI_PASSWORD = "secure_wifi_password"
BROKER_IP = "192.168.1.100"
BROKER_PORT = 1883
AUTH_TOKEN = "phass_omni_secret_token_2026"
CLIENT_ID = "esp32_edge_brain"
CLIENT_TYPE = "esp32"

# Hardware Pin Registries
pin_cache = {}
adc_cache = {}
pwm_cache = {}

# Supported ADC pins: 32, 33, 34, 35, 36, 39

def get_pin(pin_num, mode=Pin.OUT):
    if pin_num not in pin_cache:
        pin_cache[pin_num] = Pin(pin_num, mode)
    return pin_cache[pin_num]

def set_pin(pin: int, state: int) -> dict:
    '''Sets a GPIO pin HIGH (1) or LOW (0).'''
    try:
        p = get_pin(pin, Pin.OUT)
        p.value(1 if state else 0)
        return {"status": "SUCCESS", "action": "set_pin", "pin": pin, "state": int(state)}
    except Exception as e:
        return {"status": "ERROR", "action": "set_pin", "pin": pin, "error": str(e)}

def read_adc(pin: int) -> dict:
    '''Reads raw analog voltage from an ADC-capable GPIO pin.'''
    try:
        if pin not in adc_cache:
            adc_cache[pin] = ADC(Pin(pin))
        adc = adc_cache[pin]
        if hasattr(adc, "read"):
            val = adc.read()
        elif hasattr(adc, "read_u16"):
            val = adc.read_u16() >> 4
        else:
            val = 2048
        voltage = round((val / 4095.0) * 3.3, 2)
        return {"status": "SUCCESS", "action": "read_adc", "pin": pin, "raw": val, "voltage": voltage}
    except Exception as e:
        return {"status": "ERROR", "action": "read_adc", "pin": pin, "error": str(e)}

def pwm(pin: int, duty: int, freq: int = 1000) -> dict:
    '''Controls Pulse Width Modulation for LEDs and motors.'''
    try:
        if pin not in pwm_cache:
            pwm_cache[pin] = PWM(Pin(pin), freq=freq)
        pwm_obj = pwm_cache[pin]
        if hasattr(pwm_obj, "freq"):
            pwm_obj.freq(freq)
        if hasattr(pwm_obj, "duty"):
            pwm_obj.duty(duty)
        elif hasattr(pwm_obj, "duty_u16"):
            pwm_obj.duty_u16(duty * 64)
        return {"status": "SUCCESS", "action": "pwm", "pin": pin, "duty": duty, "freq": freq}
    except Exception as e:
        return {"status": "ERROR", "action": "pwm", "pin": pin, "error": str(e)}

def execute_command(cmd_dict: dict) -> dict:
    '''Dispatches incoming JSON commands from P.H.A.S.S.'''
    action = cmd_dict.get("action", "")
    if action == "set_pin":
        return set_pin(int(cmd_dict.get("pin", 2)), int(cmd_dict.get("state", 0)))
    elif action == "read_adc":
        return read_adc(int(cmd_dict.get("pin", 34)))
    elif action in ("pwm", "set_pwm"):
        return pwm(int(cmd_dict.get("pin", 13)), int(cmd_dict.get("duty", 512)), int(cmd_dict.get("freq", 1000)))
    elif action == "ping":
        return {"status": "pong", "client_id": CLIENT_ID, "timestamp": time.time()}
    return {"status": "UNKNOWN_ACTION", "action": action}

def collect_telemetry() -> dict:
    '''Reads device status, temperature, and pin states.'''
    active_pins = {str(k): v.value() for k, v in pin_cache.items()}
    return {
        "type": "telemetry",
        "client_id": CLIENT_ID,
        "client_type": CLIENT_TYPE,
        "telemetry": {
            "status": "online",
            "uptime_ms": int(time.time() * 1000),
            "temp_c": 28.5,
            "battery_v": 3.74,
            "wifi_rssi": -55,
            "active_pins": active_pins,
        }
    }

def connect_wifi():
    '''Auto-connects to local Wi-Fi with retries.'''
    try:
        import network
        wlan = network.WLAN(network.STA_IF)
        wlan.active(True)
        if not wlan.isconnected():
            print("[Edge Brain] Connecting to Wi-Fi: " + WIFI_SSID)
            wlan.connect(WIFI_SSID, WIFI_PASSWORD)
            for _ in range(20):
                if wlan.isconnected():
                    break
                time.sleep(0.5)
        print("[Edge Brain] Wi-Fi Connected: ", wlan.ifconfig())
    except Exception as e:
        print("[Edge Brain] Wi-Fi connection notice: ", e)

def run():
    '''Main event loop connecting to broker, listening for commands, and publishing telemetry.'''
    print("[Edge Brain] Initializing P.H.A.S.S Edge Brain for " + CLIENT_TYPE.upper() + "...")
    set_pin(2, 1)
    time.sleep(0.2)
    set_pin(2, 0)

    connect_wifi()

    while True:
        s = None
        try:
            print("[Edge Brain] Connecting to P.H.A.S.S Broker at " + BROKER_IP + ":" + str(BROKER_PORT))
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.connect((BROKER_IP, BROKER_PORT))
            s.setblocking(False)

            auth_packet = {
                "type": "auth",
                "token": AUTH_TOKEN,
                "client_id": CLIENT_ID,
                "client_type": CLIENT_TYPE,
                "signal_strength": -55
            }
            s.send((json.dumps(auth_packet) + "\n").encode())
            print("[Edge Brain] Authenticated with P.H.A.S.S Central Broker.")

            last_telemetry = time.time()
            recv_buffer = ""

            while True:
                now = time.time()
                if now - last_telemetry >= 5.0:
                    last_telemetry = now
                    t_data = collect_telemetry()
                    s.send((json.dumps(t_data) + "\n").encode())

                try:
                    r, _, _ = select.select([s], [], [], 0.2)
                    if r:
                        chunk = s.recv(1024).decode("utf-8")
                        if not chunk:
                            print("[Edge Brain] Connection closed by server.")
                            break
                        recv_buffer += chunk
                        while "\n" in recv_buffer:
                            line, recv_buffer = recv_buffer.split("\n", 1)
                            line = line.strip()
                            if not line:
                                continue
                            try:
                                cmd = json.loads(line)
                                result = execute_command(cmd)
                                s.send((json.dumps(result) + "\n").encode())
                            except Exception as parse_err:
                                s.send((json.dumps({"status": "ERROR", "error": str(parse_err)}) + "\n").encode())
                except Exception:
                    time.sleep(0.1)

        except Exception as conn_err:
            print("[Edge Brain] Broker connection error: ", conn_err)
            time.sleep(5.0)
        finally:
            if s:
                try:
                    s.close()
                except Exception:
                    pass

if __name__ == "__main__":
    run()
